baseurl = "https://matthewemes.com/"
title = ""
defaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
# ```lang is too engrained to give-up, enable code fences for server-side
# highlighting too.
pygmentsCodefences = true
googleAnalytics = "G-EBKYPQELQ2"

# RSS
languageCode = "en"
copyright = "Copyright © 2017 Matthew Emes. Except where explicitly noted, content on this site is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License (see https://creativecommons.org/licenses/by-sa/4.0/)."

[permalinks]
    post = "/:year/:month/:title"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[author]
    name = "Matthew Emes"
    github = "memes"
    twitter = "matthewemes"
    linkedin = "matthewemes"
    keybase = "memes"
    telegram = "matthewemes"

[params]
    license = "Content on this site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/)"
    logo = "images/avatar.png"
    favicon = "images/favicon.ico"
    dateFormat = "January 2, 2006"
    rss = true
    comments = false
    useChroma = true
    gcse = "001323389151618099461:jjsckkerz20"

[[menu.main]]
    url = ""
    name = "Home"
    weight = 1

[[menu.main]]
    identifier = "groups"
    name = "Group by"
    weight = 2

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 3

[[menu.main]]
    parent = "groups"
    name = "Categories"
    url = "/categories/"
    weight = 1

[[menu.main]]
    parent = "groups"
    name = "Tags"
    url = "/tags/"
    weight = 2

[[menu.main]]
    parent = "groups"
    name = "Series"
    url = "/series/"
    weight = 3
